"""Generate ``photoshopapi/_native.pyi`` from the built extension.

Run after building the wheel, with the package importable:

    python crates/psd-py/tools/generate_stubs.py

Signatures come from PyO3's ``__text_signature__`` and from the Python
functions ``photoshopapi._text`` installs on the text-layer classes, so the
stub lists every method IDEs cannot see through the compiled module.
"""

import inspect
import os
import re

import photoshopapi
from photoshopapi import _native

OUTPUT = os.path.join(os.path.dirname(__file__), "..", "python", "photoshopapi", "_native.pyi")


def signature(member, name):
    text = getattr(member, "__text_signature__", None)
    if text:
        text = text.replace("$self", "self").replace("$cls", "cls").replace("$type", "cls")
        text = re.sub(r",\s*/\)", ")", text).replace("(/)", "()").replace(", /", "")
        text = re.sub(r"=<[^>]*>", "=...", text)
        return text
    try:
        return str(inspect.signature(member))
    except (TypeError, ValueError):
        return "(self, *args, **kwargs)"


def doc_line(member):
    doc = inspect.getdoc(member)
    return doc.splitlines()[0] if doc else None


def emit_class(cls, lines):
    bases = [base.__name__ for base in cls.__bases__ if base is not object]
    lines.append(f"class {cls.__name__}({', '.join(bases)}):" if bases else f"class {cls.__name__}:")
    body = []
    for name, member in sorted(vars(cls).items()):
        if name.startswith("_") and name not in ("__init__", "__getitem__", "__setitem__", "__len__", "__iter__"):
            continue
        if isinstance(member, (property,)) or type(member).__name__ == "getset_descriptor":
            body.append(f"    {name}: Any")
            continue
        if isinstance(member, staticmethod) or type(member).__name__ == "builtin_function_or_method":
            body.append("    @staticmethod")
            body.append(f"    def {name}{signature(member, name).replace('(self, ', '(').replace('(self)', '()')}: ...")
            continue
        if callable(member):
            body.append(f"    def {name}{signature(member, name)}: ...")
    # PyO3 keeps the constructor signature on the class itself.
    text = getattr(cls, "__text_signature__", None)
    if text and text.startswith("("):
        params = re.sub(r"=<[^>]*>", "=...", text)
        params = "(self)" if params == "()" else "(self, " + params[1:]
        body.insert(0, f"    def __init__{params}: ...")
    lines.extend(body or ["    ..."])
    lines.append("")


def main():
    lines = [
        '"""Type stubs for the compiled ``photoshopapi._native`` module (generated by',
        'crates/psd-py/tools/generate_stubs.py; do not edit by hand)."""',
        "",
        "from typing import Any",
        "",
    ]
    for name in ("read", "rust_version", "homography_matrix", "text_property_names"):
        lines.append(f"def {name}{signature(getattr(_native, name), name)}: ...")
    lines.append("")
    classes = [member for member in vars(_native).values() if inspect.isclass(member)]
    # Bases first so the stub reads top-down.
    classes.sort(key=lambda cls: (len(cls.__mro__), cls.__name__))
    for cls in classes:
        emit_class(cls, lines)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as stub:
        stub.write("\n".join(lines))
    print("wrote", os.path.abspath(OUTPUT), "for", photoshopapi.rust_version())


main()
