//! The fixed noise table the compositor's grain draws from.
//!
//! The table is not stored: it is generated by the Park-Miller minimal
//! standard generator from a fixed seed, one byte per step (the second byte
//! of the state), 16384 entries. Anything that needs repeatable grain
//! (Dissolve) indexes it by position, so a pixel's noise never depends on
//! what else was drawn.

use std::sync::OnceLock;

const TABLE_SIZE: usize = 16384;
const SEED: u64 = 0x4358_ebc4;
const MULTIPLIER: u64 = 16807;
const MODULUS: u64 = 0x7fff_ffff;

/// The 16384-byte table.
pub(crate) fn table() -> &'static [u8; TABLE_SIZE] {
    static TABLE: OnceLock<[u8; TABLE_SIZE]> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut table = [0u8; TABLE_SIZE];
        let mut state = SEED;
        for entry in &mut table {
            state = state * MULTIPLIER % MODULUS;
            *entry = ((state >> 8) & 0xff) as u8;
        }
        table
    })
}

/// The table index a pixel at `(x, y)` draws from: a hash of the row, mixed
/// with the column, folded into the table.
pub(crate) fn index(x: i32, y: i32) -> usize {
    let row = (y as u32).wrapping_mul(0x0006_4e6d).wrapping_add(0x3039) >> 3;
    let mixed = (row ^ x as u32).wrapping_mul(0x4e6d).wrapping_add(0x3039) >> 3;
    (mixed & 0x3fff) as usize
}

/// The noise byte for the pixel at `(x, y)`.
pub(crate) fn at(x: i32, y: i32) -> u8 {
    table()[index(x, y)]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_generated_and_covers_every_value() {
        let table = table();
        let mut seen = [false; 256];
        for &value in table.iter() {
            seen[usize::from(value)] = true;
        }
        assert!(seen.iter().all(|&present| present));
        // The first step: 0x4358ebc4 * 16807 mod 0x7fffffff, second byte.
        let first = (0x4358_ebc4u64 * 16807 % 0x7fff_ffff) >> 8 & 0xff;
        assert_eq!(u64::from(table[0]), first);
    }

    #[test]
    fn indices_stay_inside_the_table_and_vary_by_position() {
        for (x, y) in [(0, 0), (1, 0), (0, 1), (-5, 9), (4000, 3000)] {
            assert!(index(x, y) < TABLE_SIZE);
        }
        assert_ne!(index(0, 0), index(1, 0));
        assert_ne!(index(0, 0), index(0, 1));
    }
}
